version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: 'kafka'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_GROUP_MAX_SESSION_TIMEOUT_MS=4000000
      - KAFKA_LISTENERS=LISTENER_EXTERNAL://:9092, LISTENER_INTERNAL://kafka:29090
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_EXTERNAL://localhost:9092, LISTENER_INTERNAL://kafka:29090
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_EXTERNAL
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_EXTERNAL:PLAINTEXT, LISTENER_INTERNAL:PLAINTEXT
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes 
      # - KAFKA_CREATE_TOPICS=th1:1:1, RAW:1:1, AGGREGATED:1:1, e_tot:1:1,  DAILY_RAW:1:1, AGGREGATED_DIFF:1:1

    depends_on:
      - zookeeper

  init-kafka:
    image: 'bitnami/kafka:latest'
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka:29090 --list

      echo -e 'Creating kafka topics'
      /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka:29090 --create --if-not-exists --topic th1 --replication-factor 1 --partitions 1
      /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka:29090 --create --if-not-exists --topic RAW --replication-factor 1 --partitions 1
      /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka:29090 --create --if-not-exists --topic AGGREGATED --replication-factor 1 --partitions 1
      /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka:29090 --create --if-not-exists --topic e_tot --replication-factor 1 --partitions 1
      /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka:29090 --create --if-not-exists --topic DAILY_RAW --replication-factor 1 --partitions 1
      /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka:29090 --create --if-not-exists --topic AGGREGATED_DIFF --replication-factor 1 --partitions 1


      echo -e 'Successfully created the following topics:'
      /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka:29090 --list
      "