version: "3.8"

services:
  python_consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_consumer
    networks:
      - messaging_broker_layer_default
      
networks:
  messaging_broker_layer_default:
    external: true


