version: '3.6'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana-server2
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    ports:
      - '3000:3000'
    volumes:
      - ./grafana_data:/var/lib/grafana

volumes:
  grafana_data:
    name: grafana_data